# Generated by Django 2.2.3 on 2019-07-27 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contraction_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contraction',
            options={'ordering': ('start',)},
        ),
        migrations.AddField(
            model_name='contraction',
            name='pain',
            field=models.PositiveSmallIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='contraction',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractions', to=settings.AUTH_USER_MODEL),
        ),
    ]
