# Generated by Django 2.2.3 on 2019-07-28 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190727_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contraction',
            options={'get_latest_by': ('end',), 'ordering': ('start',)},
        ),
    ]
